### ISSUE TITLE
Configure Realm to use JwtAuthProvider

### ISSUE THREAD

**Issue by watchdogtimer** [realm/charts#1]
I am looking to convert from using an individual ROS instance to a Kubernetes based deployment. However, it is not clear to me how one would use a JwtAuthProvider for allowing an API to use JWT tokens for making authenticated calls to this k8s based ROS. Where can I find the information to do this?

**Comment by malafreniere** [comment]
I'm not too sure, but just looking at the files, I guess you could override the values in your overrides.yml and override the image section:

https://github.com/realm/charts/blob/master/realm-object-server/values.yaml
line 124-128
```yaml
# Defines the location, version and pull policy for our images.
image:
  repository: realm/realm-object-server
  tag: latest
  pullPolicy: Always
```

But again, it's just a guess

(I'm looking at using JwtAuthProvider too)

**Comment by nirinchev** [comment]
@ianpward @alebsack perhaps you can help?

**Comment by ianpward** [comment]
The value for authProviders is set here in the values.yml -
https://github.com/realm/charts/blob/master/realm-object-server/values.yaml#L102

The name would be `jwt` and the type is `JwtAuthProvider`

**Comment by watchdogtimer** [comment]
Thanks, that makes sense!

How would I include MyCustomJwtAuthProvider in the same way? I've extended auth.JwtAuthProvider. MyCustomJwtAuthProvider has a crucial feature that is lacking in auth.JwtAuthProvider

**Comment by koehrlenguillaume** [comment]
Hey @ianpward, 

You're saying that we have to add a new provider in the defaultProvider section named ```jwt``` and type ```JwtAuthProvider``` 

Can you tell us, what are other parameters available for this provider ? 
Do we have a property for the public key ? 

I tried the following configuration without success: 
```
defaultProviders:
     - name: password
        type: PasswordAuthProvider
        config:
          autoCreateAdminUser: true
     - name: jwt
        type: JwtAuthProvider
        config: 
          publicKey: "-----BEGIN PUBLIC KEY-----\nMIIBIj.....Gvm5McuwIDAQAB\n-----END PUBLIC KEY-----""
```

Thanks for your help
