### ISSUE TITLE
Helm Chart template for sync-workers.yaml not working as expected

### ISSUE THREAD

**Issue by watchdogtimer** [realm/charts#2]
I've been trying to provide the section for resources in the Helm Chart via:

values.yaml
```
sync:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
```

Per the recommendation in the comment. This does not successfully replace the placeholder in the sync-workers.yaml:

{{ toYaml .resources | default $values.sync.resources | indent 12 }}

If I change the template to 

{{ toYaml $values.sync.resources | indent 12 }}

This works fine, but I don't understand the intent of the placeholder. I would prefer not to modify this chart where it's not needed to stay in line with what you have here in the repo
